import { cn } from '@/lib/utils/cn'
import { useClinicalInterpretation } from '../hooks/useClinicalInterpretation'
import { recommendationCategoryLabel } from '../lib/clinicalEngine'
import { ClinicalSection, ClinicalEmptyState } from './ClinicalSection'
import type { RecommendationPriority } from '../types/clinicalInterpretation'

const PRIORITY_TONE: Record<RecommendationPriority, string> = {
  high: 'border-warning/50 bg-warning-muted text-warning',
  medium: 'border-info/40 bg-info-muted text-info',
  low: 'border-line-strong bg-surface-subtle text-muted',
}

/**
 * Recommendations (Phase 6, Section 17). Displayed only when supplied by the
 * backend/clinical knowledge layer — never generated by the frontend.
 */
export function RecommendationList() {
  const { interpretation } = useClinicalInterpretation()
  const recommendations = interpretation.recommendations

  return (
    <ClinicalSection id="recommendations" title="Recommendations">
      {recommendations.length === 0 ? (
        <ClinicalEmptyState message="Recommendations are not available for this analysis. They are supplied by the clinical knowledge layer." />
      ) : (
        <ul className="flex flex-col gap-2.5">
          {recommendations.map((r) => (
            <li key={r.id} className="rounded-lg border border-line-subtle bg-surface p-3.5">
              <div className="flex flex-wrap items-center gap-1.5">
                <span className="rounded bg-surface-subtle px-1.5 py-0.5 text-xs text-secondary">
                  {recommendationCategoryLabel(r.category)}
                </span>
                {r.priority && (
                  <span
                    className={cn(
                      'rounded-full border px-2 py-0.5 font-mono text-[10px] uppercase tracking-wide',
                      PRIORITY_TONE[r.priority],
                    )}
                  >
                    {r.priority} priority
                  </span>
                )}
              </div>
              <p className="mt-1.5 text-sm font-medium text-primary">{r.title}</p>
              {r.description && <p className="mt-0.5 text-xs text-secondary">{r.description}</p>}
              {r.rationale && (
                <p className="mt-1.5 border-l-2 border-line-subtle pl-2 text-xs italic text-muted">
                  {r.rationale}
                </p>
              )}
            </li>
          ))}
        </ul>
      )}
    </ClinicalSection>
  )
}
