"""
Schema Validator and Missing Value Analyzer for Tabular Clinical Ingestion.
"""

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional
import pandas as pd


@dataclass
class TabularValidationReport:
    """
    Structured summary report generated by tabular schema validation.
    """
    row_count: int
    column_count: int
    missing_summary: List[Dict[str, Any]] = field(default_factory=list)
    duplicate_columns: List[str] = field(default_factory=list)
    empty_columns: List[str] = field(default_factory=list)
    constant_columns: List[str] = field(default_factory=list)
    is_valid: bool = True
    errors: List[str] = field(default_factory=list)


def analyze_missing_values(df: pd.DataFrame) -> List[Dict[str, Any]]:
    """
    Analyze missingness per feature column in a pandas DataFrame.

    Returns
    -------
    List[Dict[str, Any]]
        List of dicts containing 'column', 'dtype', 'missing_count', 'missing_fraction'.
    """
    summary = []
    total_rows = len(df)
    for i in range(df.shape[1]):
        col_name = str(df.columns[i])
        series = df.iloc[:, i]
        null_count = int(series.isnull().sum())
        null_frac = float(null_count / total_rows) if total_rows > 0 else 0.0
        summary.append({
            "column": col_name,
            "dtype": str(series.dtype),
            "missing_count": null_count,
            "missing_fraction": null_frac,
        })
    return summary


def validate_tabular_schema(df: pd.DataFrame) -> TabularValidationReport:
    """
    Validate tabular schema, checking row/column counts, duplicates, empty columns, and constant columns.

    Parameters
    ----------
    df : pd.DataFrame
        Input clinical DataFrame to validate.

    Returns
    -------
    TabularValidationReport
        Validation report detailing dataset health.

    Raises
    ------
    ValueError
        If df is None, empty, or has no rows/columns.
    """
    if df is None:
        raise ValueError("Tabular input DataFrame cannot be None.")

    if not isinstance(df, pd.DataFrame):
        raise TypeError(f"Expected pandas DataFrame, got {type(df).__name__}")

    rows, cols = df.shape
    if rows == 0 or cols == 0:
        raise ValueError(f"Tabular DataFrame is empty. Shape: ({rows}, {cols})")

    errors = []
    duplicate_cols = []
    empty_cols = []
    constant_cols = []

    # Check duplicate column names
    col_names = [str(c) for c in df.columns]
    seen = set()
    for c in col_names:
        if c in seen:
            duplicate_cols.append(c)
        else:
            seen.add(c)

    if duplicate_cols:
        errors.append(f"Duplicate column names detected: {sorted(list(set(duplicate_cols)))}")

    # Analyze missingness and columns
    missing_summary = analyze_missing_values(df)
    for idx, info in enumerate(missing_summary):
        col_name = info["column"]
        series = df.iloc[:, idx]
        if info["missing_count"] == rows:
            empty_cols.append(col_name)
        else:
            non_null_series = series.dropna()
            if len(non_null_series.unique()) <= 1:
                constant_cols.append(col_name)

    is_valid = len(errors) == 0

    return TabularValidationReport(
        row_count=rows,
        column_count=cols,
        missing_summary=missing_summary,
        duplicate_columns=sorted(list(set(duplicate_cols))),
        empty_columns=empty_cols,
        constant_columns=constant_cols,
        is_valid=is_valid,
        errors=errors,
    )
